@{
    MenuSections = @('Telemetry and Reports','Bulk Actions','Safe Management','Account Management','Platform Management','Troubleshooting and Tools')
    Commands = @(
        @{ Id='telemetry.components'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports'); DisplayName='Dashboard: Most used connection components'; Script='Commands/Telemetry/Get-ConnectionComponents.ps1'; Parameters=@('LookbackDays'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='telemetry.active-users'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports'); DisplayName='Dashboard: Identity user activity'; Script='Commands/Telemetry/Get-ActiveUsers.ps1'; Parameters=@(); RequiredAuth='Identity'; RiskLevel='Read'; SupportsUnattended=$true; Deployments=@('ispss') }
        @{ Id='telemetry.account-failures'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports','Account Management','Troubleshooting and Tools'); DisplayName='Dashboard: CPM and PSM account failures'; Script='Commands/Telemetry/Get-AccountFailures.ps1'; Parameters=@('LookbackDays'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='telemetry.psm-users'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports','Troubleshooting and Tools'); DisplayName='Report PSM users from recordings'; Script='Commands/Telemetry/Export-PsmUsers.ps1'; Parameters=@('LookbackDays'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='telemetry.license-capacity'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports'); DisplayName='Dashboard: Privilege Cloud license capacity'; Script='Commands/Telemetry/Get-LicenseCapacity.ps1'; Parameters=@(); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true; Deployments=@('ispss') }
        @{ Id='account.inventory'; Category='Account Management'; Sections=@('Telemetry and Reports','Bulk Actions','Account Management'); DisplayName='Export account inventory'; Script='Commands/Report/Export-AccountInventory.ps1'; Parameters=@('Search','SafeName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.members.report'; Category='Safe Management'; Sections=@('Telemetry and Reports','Bulk Actions','Safe Management'); DisplayName='Export all safe members'; Script='Commands/Report/Export-SafeMembership.ps1'; Parameters=@('SafeName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.inventory'; Category='Safe Management'; Sections=@('Telemetry and Reports','Bulk Actions','Safe Management'); DisplayName='Export safe inventory'; Script='Commands/Report/Export-Safes.ps1'; Parameters=@('Search'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='bulk.safes.apply'; Category='Bulk Actions'; Sections=@('Bulk Actions','Safe Management'); DisplayName='Apply safe create/update/delete CSV'; Script='Commands/Bulk/Invoke-BulkSafes.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='bulk.safe-members.apply'; Category='Bulk Actions'; Sections=@('Bulk Actions','Safe Management'); DisplayName='Apply safe-member add/update/delete CSV'; Script='Commands/Bulk/Invoke-BulkSafeMembers.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='bulk.safe-members.import-compatible'; Category='Bulk Actions'; Sections=@('Bulk Actions','Safe Management'); DisplayName='Import missing members with exact CSV permissions'; Script='Commands/Bulk/Import-SafeMembersCompatible.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='bulk.accounts.apply'; Category='Bulk Actions'; Sections=@('Bulk Actions','Account Management'); DisplayName='Apply account create/update/delete CSV'; Script='Commands/Bulk/Invoke-BulkAccounts.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='platform.accounts.move'; Category='Bulk Actions'; Sections=@('Bulk Actions','Platform Management','Account Management'); DisplayName='Move accounts to platforms from CSV'; Script='Commands/Platform/Move-Accounts.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='resolution.account-failures'; Category='Bulk Actions'; Sections=@('Bulk Actions','Account Management','Troubleshooting and Tools'); DisplayName='Bulk repair account-management failures'; Script='Commands/Resolution/Resolve-AccountFailures.ps1'; Parameters=@('AccountIds'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='safe.list'; Category='Safe Management'; Sections=@('Safe Management'); DisplayName='List/search safes'; Script='Commands/Safe/Get-Safes.ps1'; Parameters=@('Search'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.detail'; Category='Safe Management'; Sections=@('Safe Management'); DisplayName='Get safe details'; Script='Commands/Safe/Get-SafeDetail.ps1'; Parameters=@('SafeName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.create'; Category='Safe Management'; Sections=@('Safe Management'); DisplayName='Create a safe'; Script='Commands/Safe/New-Safe.ps1'; Parameters=@('SafeName','Description','ManagingCPM'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='safe.members.list'; Category='Safe Management'; Sections=@('Safe Management'); DisplayName='List members of one safe'; Script='Commands/Safe/Get-SafeMembers.ps1'; Parameters=@('SafeName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.members.add'; Category='Safe Management'; Sections=@('Safe Management'); DisplayName='Add a safe member'; Script='Commands/Safe/Add-SafeMember.ps1'; Parameters=@('SafeName','MemberName','MemberType','Role'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='safe.cpm.export'; Category='Safe Management'; Sections=@('Safe Management','Bulk Actions','Telemetry and Reports'); DisplayName='Export verified safe CPM assignments'; Script='Commands/Safe/Export-SafeCpmAssignments.ps1'; Parameters=@(); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.cpm.apply'; Category='Safe Management'; Sections=@('Safe Management','Bulk Actions','Troubleshooting and Tools'); DisplayName='Apply safe CPM assignments with conflict checks'; Script='Commands/Safe/Import-SafeCpmAssignments.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='account.search'; Category='Account Management'; Sections=@('Account Management'); DisplayName='Search accounts'; Script='Commands/Account/Search-Accounts.ps1'; Parameters=@('Search','SafeName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='account.detail'; Category='Account Management'; Sections=@('Account Management'); DisplayName='Get account details'; Script='Commands/Account/Get-AccountDetail.ps1'; Parameters=@('AccountId'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='platform.list'; Category='Platform Management'; Sections=@('Platform Management','Telemetry and Reports','Bulk Actions'); DisplayName='List and export target platforms'; Script='Commands/Platform/Get-Platforms.ps1'; Parameters=@('Search'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='platform.accounts.report'; Category='Platform Management'; Sections=@('Platform Management','Telemetry and Reports','Bulk Actions','Account Management'); DisplayName='Report accounts by platform'; Script='Commands/Platform/Export-PlatformAccounts.ps1'; Parameters=@('PlatformId'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='platform.pmterminal.audit'; Category='Platform Management'; Sections=@('Platform Management','Telemetry and Reports','Troubleshooting and Tools'); DisplayName='Audit PMTerminal CPM plug-in references'; Script='Commands/Platform/Audit-PMTerminal.ps1'; Parameters=@(); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='troubleshooting.dependencies'; Category='Troubleshooting and Tools'; Sections=@('Troubleshooting and Tools'); DisplayName='Check local FastPAS dependencies'; Script='Commands/Troubleshooting/Test-Dependencies.ps1'; Parameters=@(); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='troubleshooting.connectivity'; Category='Troubleshooting and Tools'; Sections=@('Troubleshooting and Tools'); DisplayName='Test CyberArk and SIA endpoint connectivity'; Script='Commands/Troubleshooting/Test-Connectivity.ps1'; Parameters=@('EndpointCsvPath'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='troubleshooting.local-to-domain'; Category='Troubleshooting and Tools'; Sections=@('Troubleshooting and Tools','Bulk Actions','Account Management'); DisplayName='Convert local accounts to domain accounts from CSV'; Script='Commands/Troubleshooting/Convert-LocalToDomainAccounts.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='compliance.posture'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports'); DisplayName='Dashboard: compliance and hygiene command center'; Script='Commands/Governance/Get-CompliancePosture.ps1'; Parameters=@('PasswordAgeDays','InactiveDays'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='onboarding.discovered'; Category='Account Management'; Sections=@('Account Management','Bulk Actions','Telemetry and Reports'); DisplayName='Workbench: discovered accounts and onboarding recommendations'; Script='Commands/Onboarding/Get-DiscoveredAccounts.ps1'; Parameters=@('Search','PlatformType'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='onboarding.discovered.apply'; Category='Account Management'; Sections=@('Account Management','Bulk Actions'); DisplayName='Apply discovered-account onboarding decisions'; Script='Commands/Onboarding/Invoke-DiscoveredAccountDecisions.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='relationships.report'; Category='Account Management'; Sections=@('Account Management','Telemetry and Reports','Bulk Actions','Troubleshooting and Tools'); DisplayName='Report linked and dependent account relationships'; Script='Commands/Relationship/Get-AccountRelationships.ps1'; Parameters=@('SafeName','MaxAccounts'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='relationships.apply'; Category='Account Management'; Sections=@('Account Management','Bulk Actions'); DisplayName='Apply logon/reconcile account links from CSV'; Script='Commands/Relationship/Invoke-AccountLinks.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='governance.entitlements'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports','Safe Management'); DisplayName='Report effective safe access, owners, users, and licenses'; Script='Commands/Governance/Get-EffectiveAccess.ps1'; Parameters=@('Principal','SafeName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='telemetry.system-health'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports','Troubleshooting and Tools'); DisplayName='Dashboard: component health and capacity'; Script='Commands/Telemetry/Get-SystemHealth.ps1'; Parameters=@(); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='platform.drift'; Category='Platform Management'; Sections=@('Platform Management','Telemetry and Reports','Bulk Actions','Troubleshooting and Tools'); DisplayName='Export or compare platform configuration baselines'; Script='Commands/Platform/Get-PlatformDrift.ps1'; Parameters=@('BaselinePath','PlatformId'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='platform.drift.apply'; Category='Platform Management'; Sections=@('Platform Management','Bulk Actions'); DisplayName='Apply guarded platform property changes from CSV'; Script='Commands/Platform/Invoke-PlatformChanges.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='psm.sessions'; Category='Telemetry and Reports'; Sections=@('Telemetry and Reports','Bulk Actions','Troubleshooting and Tools'); DisplayName='Console: active and historical PSM sessions'; Script='Commands/PSM/Get-PsmSessions.ps1'; Parameters=@('LookbackDays','UserName'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='psm.sessions.action'; Category='Troubleshooting and Tools'; Sections=@('Troubleshooting and Tools','Bulk Actions'); DisplayName='Suspend, resume, or terminate PSM sessions'; Script='Commands/PSM/Invoke-PsmSessionAction.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='aam.exposure'; Category='Platform Management'; Sections=@('Telemetry and Reports','Bulk Actions','Platform Management','Troubleshooting and Tools'); DisplayName='Audit Application ID and credential-provider exposure'; Script='Commands/Governance/Get-ApplicationExposure.ps1'; Parameters=@('ApplicationId'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true; Deployments=@('onprem') }
        @{ Id='aam.exposure.apply'; Category='Platform Management'; Sections=@('Platform Management','Bulk Actions','Troubleshooting and Tools'); DisplayName='Apply guarded Application ID authentication changes'; Script='Commands/Governance/Invoke-ApplicationAuthenticationChanges.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true; Deployments=@('onprem') }
        @{ Id='request.queue'; Category='Account Management'; Sections=@('Account Management','Telemetry and Reports','Bulk Actions'); DisplayName='Console: dual-control request and approval queue'; Script='Commands/Request/Get-AccessRequests.ps1'; Parameters=@('Status','OnlyWaiting'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='request.action'; Category='Account Management'; Sections=@('Account Management','Bulk Actions'); DisplayName='Create, approve, or reject access requests from CSV'; Script='Commands/Request/Invoke-AccessRequestActions.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='safe.migration.plan'; Category='Safe Management'; Sections=@('Safe Management','Account Management','Bulk Actions'); DisplayName='Plan and validate safe-to-safe account migration'; Script='Commands/Migration/Get-SafeMigrationPlan.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Read'; SupportsUnattended=$true }
        @{ Id='safe.migration.apply'; Category='Safe Management'; Sections=@('Safe Management','Account Management','Bulk Actions'); DisplayName='Apply verified safe-to-safe account migration'; Script='Commands/Migration/Invoke-SafeMigration.ps1'; Parameters=@('CsvPath'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
        @{ Id='account.safe-transfer'; Category='Account Management'; Sections=@('Account Management','Safe Management','Bulk Actions'); DisplayName='Transfer safe accounts with current secret only'; Script='Commands/Account/Move-SafeAccountsWithCurrentSecret.ps1'; Parameters=@('CsvPath','Concurrency','ResumePath','DetailMode','MaxGetRetries','Reason','RelationshipMode','CpmOperationalState'); RequiredAuth='Platform'; RiskLevel='Write'; SupportsUnattended=$true }
    )
}
